### ISSUE TITLE
Relativa/Symbolic Paths instead of Absoluta Paths

### ISSUE THREAD

**Issue by Komodoro** [joaoramos1993/LinuxConfig#1]
https://github.com/joaoramos1993/LinuxConfig/blob/2149a497ac054cebb782e43969fef552e6ca6980/.bashrc#L124

These kind of scripts normaly are run directly on the users home folder
Why not create this Path automaticaly pwd command or use something like GLOBAL ENV's such as $HOME

Since se are sharing scripts se need to mais them as ambiguous as possible to it works for everyone.

Ir you can use:
DIR=$(pwd)
basel_home=$DIR/baselstuff

This is a subliminal detail that when se start using tools and git to support versioning Control and Share it with others come into play.

**Comment by Komodoro** [comment]
Ok... Maybe i've got ahead of myself.
But still...
That Path should be (i guess):
$HOME/bin
Why The "joaoramos" after home.
Do you have a folder called joaoramos inside The joaoramos home folder?
It kinda doesnt add up with what you have on the last line.
https://github.com/joaoramos1993/LinuxConfig/blob/2149a497ac054cebb782e43969fef552e6ca6980/.bashrc#L125

Another alternative is, we can use a $USER with:
USER =$(whoami) and substitute your username.
If so needed.
But having generic users for everyone to use isn't such a bad politic since you have different network approaches to monitor whoever logs in a machine.

Either that, you can also have a generic attribute set in /etc/profiles for every user.
That way you can services like "PBIS" or Samba to connect to an LDAP or Active directory to permit your login and don't create a user static home folder and have binaries added in the /usr/bin folder.

One of the two approaches is fine, but I'll let you think about it. Since you brought me up to this repository to work out a strong home folder support on daily basis usage.

**Comment by joaoramos1993** [comment]
Always learning and I will be more careful.
Since bazel is not commonly used I removed those lines.
